// Auth Action Types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Facility Action Types
export const FETCH_AVAILABLE_FACILITIES_SUCCESS = 'FETCH_AVAILABLE_FACILITIES_SUCCESS';
export const FETCH_AVAILABLE_FACILITIES_FAIL = 'FETCH_AVAILABLE_FACILITIES_FAIL';

// Equipment Action Types
export const FETCH_AVAILABLE_EQUIPMENT_SUCCESS = 'FETCH_AVAILABLE_EQUIPMENT_SUCCESS';
export const FETCH_AVAILABLE_EQUIPMENT_FAIL = 'FETCH_AVAILABLE_EQUIPMENT_FAIL';
export const CREATE_EQUIPMENT_BOOKING_SUCCESS = 'CREATE_EQUIPMENT_BOOKING_SUCCESS';
export const CREATE_EQUIPMENT_BOOKING_FAIL = 'CREATE_EQUIPMENT_BOOKING_FAIL';

// Facility Booking Action Types
export const CREATE_FACILITY_BOOKING_SUCCESS = 'CREATE_FACILITY_BOOKING_SUCCESS';
export const CREATE_FACILITY_BOOKING_FAIL = 'CREATE_FACILITY_BOOKING_FAIL';
export const FETCH_AVAILABLE_SLOTS_SUCCESS = 'FETCH_AVAILABLE_SLOTS_SUCCESS';
export const FETCH_AVAILABLE_SLOTS_FAIL = 'FETCH_AVAILABLE_SLOTS_FAIL';

// Coach Profile Action Types
export const FETCH_COACH_PROFILES = 'FETCH_COACH_PROFILES';
export const FETCH_COACH_PROFILE_BY_ID = 'FETCH_COACH_PROFILE_BY_ID'; 


// Review Action Types
export const FETCH_REVIEWS_BY_COACH = 'FETCH_REVIEWS_BY_COACH';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const ADD_REVIEW = 'ADD_REVIEW';

export const SESSION_REQUEST_SUCCESS = 'SESSION_REQUEST_SUCCESS';
export const SESSION_REQUEST_FAILURE = 'SESSION_REQUEST_FAILURE';

export const FETCH_SESSION_REQUESTS = 'FETCH_SESSION_REQUESTS';
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS';
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE';


// export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
// export const FETCH_REQUESTS_FAILURE = 'FETCH_REQUESTS_FAILURE';
// export const FETCH_REQUESTS_LOADING = 'FETCH_REQUESTS_LOADING';